version: '3'

services:
  nodejs:
    build: .
    image: javmo94/api-lyric
    container_name: nodejs
    restart: unless-stopped
    environment:
      - API_URI=localhost:4000
      - MONGODB_URI=mongodb://javmo:javmo@db:27017/lyricdb?authSource=admin

    ports:
      - "4000:4000"
    command: npm run start
    depends_on:
      - db
    networks:
      - app-network

  db:
      image: mongo
      container_name: db
      restart: unless-stopped
      env_file: .env
      environment:
        - MONGO_INITDB_ROOT_USERNAME=javmo
        - MONGO_INITDB_ROOT_PASSWORD=javmo
        - MONGO_INITDB_DATABASE=lyricdb
      networks:
        - app-network
networks:
  app-network:
    driver: bridge

