name: Build and Push Docker image

on:
  push:
    branches:
      - master  # Cambia esto por la rama que quieras usar

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}  # Usa DOCKER_TOKEN si es aplicable

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: javmo94/api-lyric:latest  # Reemplaza con tu nombre de usuario y el nombre de tu imagen

